PRODUCT_DATA = {
    'name': 'Iphone 10',
    'price': 3000,
    'pieces': 2,
    'ram': 8,
    'memory': 8,
    'modem': 8,
    'color': 'grey',
    'describe': 'The best model',
    'producent': 'Apple',
    'producent_code': 'AABB123',
    'ean': 123456,
    'waterproof': True,
    'distribution': 'EU',
    'system': 'IOS',
    'model': ' ',
    'processor': 'Intel',
    'cpu_clock': '400Mhz',
    'memory_card': '10GB',
    'usb': '3.0',
    'audio_jack': "Yes",
    'screen': '100x200',
    'screen_diagonal': 7.2,
    'battery': 100,
    'high': 10,
    'width': 10,
    'deep': 10,
    'weight': 0.5,
    'cattegory': 'Phones',
    'main_photo': ''
}

SECOND_PRODUCT = {
    'name': 'Samsung 10',
    'price': 300,
    'pieces': 2,
    'ram': 8,
    'memory': 8,
    'modem': 8,
    'color': 'white',
    'describe': 'The best model',
    'producent': 'Apple',
    'producent_code': 'AABB123',
    'ean': 123455,
    'waterproof': True,
    'distribution': 'EU',
    'model': ' ',
    'system': 'IOS',
    'processor': 'Intel',
    'cpu_clock': '400Mhz',
    'memory_card': '10GB',
    'usb': '3.0',
    'audio_jack': "Yes",
    'screen': '100x200',
    'screen_diagonal': 7.2,
    'battery': 100,
    'high': 10,
    'width': 10,
    'deep': 10,
    'weight': 0.5,
    'cattegory': 'Phones',
    'main_photo': ''
}
