language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

script:
- docker-compose run electronicshop sh -c "python manage.py wait_for_db && python manage.py test"
- flake8 . --exit-zero # Exit with status code "0" even if there are errors.
