version: '3.4'

services:
  electronicshop:
    image: electronicshop
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/electronic_shop
      - postgres:/vol/postgres
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DOCKER_DB_NAME=${DOCKER_DB_NAME}
      - DB_USER=${LOCAL_USER}
      - DB_PASSWORD=${LOCAL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=${DOCKER_DB_NAME}
      - POSTGRES_USER=${LOCAL_USER}
      - POSTGRES_PASSWORD=${LOCAL_PASSWORD}
    ports:
      - 5454:5454/tcp
    restart: always

volumes:
  postgres:
