from django.contrib import admin
from . import models

admin.site.register(models.MainProductDatabase)
admin.site.register(models.Phones)
admin.site.register(models.Monitors)
admin.site.register(models.Reviews)
admin.site.register(models.Questions)
admin.site.register(models.Pendrives)
admin.site.register(models.Routers)
admin.site.register(models.Laptops)
admin.site.register(models.Pc)
admin.site.register(models.Tv)
admin.site.register(models.AccesoriesForLaptops)
admin.site.register(models.Ssd)
admin.site.register(models.Graphs)
admin.site.register(models.Ram)
admin.site.register(models.Switches)
admin.site.register(models.Motherboard)
admin.site.register(models.Cpu)
admin.site.register(models.Headphones)
admin.site.register(models.ProductOfTheDayDB)
