iPhone_12_Mini_5G_128GB_Dual_SIM_Blue={
                'name': 'Iphone 12 Mini 5G 128GB Blue',
                'price': 799.99,
                'model': 'Iphone 12',
                'pieces': 5,
                'color': 'Blue',
                'producent': 'Apple',
                'producent_code': 'MGE63PM/A',
                'ean': 194252015810 ,
                'waterproof': True,
                'system': 'iOS 14',
                'processor': 'Apple A14 Bionic',
                'cpu_clock': '6 x 2.99 GHz Hexa Core',
                'memory_card': 'Not avaiable',
                'max_memory_card': 'Not avaiable',
                'ram': '4 GB',
                'memory': '128 GB',
                'modem': '5G',
                'usb': '3.0',
                'audio_jack': "Not avaiable",
                'screen': '1080 x 2340',
                'screen_diagonal': 5.4,
                'battery': '2277 mAh',
                'high': 13.1,
                'width': 6.4,
                'deep': 0.7,
                'weight': 133,
                'cattegory': 'Phones',
                'main_photo': 'Iphone 12 Mini 5G 128GB Blue_1.jpg',
                'second_photo': 'Iphone 12 Mini 5G 128GB Blue_2.jpg',
                'third_photo': 'Iphone 12 Mini 5G 128GB Blue_3.jpg',
            }

iPhone_12_Mini_5G_128GB_Dual_SIM_red={
                'name': 'Iphone 12 Mini 5G 128GB Red',
                'model': 'Iphone 12',
                'price': 799.99,
                'pieces': 5,
                'color': 'Red',
                'producent': 'Apple',
                'producent_code': 'MGE53PM/A',
                'ean': 194252015537 ,
                'waterproof': True,
                'system': 'iOS 14',
                'processor': 'Apple A14 Bionic',
                'cpu_clock': '6 x 2.99 GHz Hexa Core',
                'memory_card': 'Not avaiable',
                'max_memory_card': 'Not avaiable',
                'ram': '4 GB',
                'memory': '128 GB',
                'modem': '5G',
                'usb': '3.0',
                'audio_jack': "Not avaiable",
                'screen': '1080 x 2340',
                'screen_diagonal': 5.4,
                'battery': '2277 mAh',
                'high': 13.1,
                'width': 6.4,
                'deep': 0.7,
                'weight': 133,
                'cattegory': 'Phones',
                'main_photo': 'Iphone 12 Mini 5G 128GB Red_1.jpg',
                'second_photo': 'Iphone 12 Mini 5G 128GB Red_2.jpg',
                'third_photo': 'Iphone 12 Mini 5G 128GB Red_3.jpg',
            }

iPhone_12_Pro_512GB_Grey={
                'name': 'Iphone 12 Pro 512GB Grey',
                'model': 'Iphone 12',
                'price': 1499.99,
                'pieces': 2,
                'color': 'Grey',
                'producent': 'Apple',
                'producent_code': 'MGMU3PM/A',
                'ean': 194252040294 ,
                'waterproof': True,
                'system': 'iOS 14',
                'processor': 'Apple A14 Bionic',
                'cpu_clock': '6 x 2.99 GHz Hexa Core',
                'memory_card': 'Not avaiable',
                'max_memory_card': 'Not avaiable',
                'ram': '6 GB',
                'memory': '512 GB',
                'modem': '5G',
                'usb': '3.0',
                'audio_jack': "Not avaiable",
                'screen': '1170 x 2532',
                'screen_diagonal': 6.1,
                'battery': '2775 mAh',
                'high': 14.7,
                'width': 7.1,
                'deep': 0.7,
                'weight': 187,
                'cattegory': 'Phones',
                'main_photo': 'Iphone 12 Pro 512GB Grey_1.jpg',
                'second_photo': 'Iphone 12 Pro 512GB Grey_2.jpg',
                'third_photo': 'Iphone 12 Pro 512GB Grey_3.jpg',
            }

iPhone_12_Pro_256GB_Grey={
                'name': 'Iphone 12 Pro 256GB Grey',
                'model': 'Iphone 12',
                'price': 1199.99,
                'pieces': 5,
                'color': 'Grey',
                'producent': 'Apple',
                'producent_code': 'MGMP3PM/A',
                'ean': 194252038932 ,
                'waterproof': True,
                'system': 'iOS 14',
                'processor': 'Apple A14 Bionic',
                'cpu_clock': '6 x 2.99 GHz Hexa Core',
                'memory_card': 'Not avaiable',
                'max_memory_card': 'Not avaiable',
                'ram': '6 GB',
                'memory': '256 GB',
                'modem': '5G',
                'usb': '3.0',
                'audio_jack': "Not avaiable",
                'screen': '1170 x 2532',
                'screen_diagonal': 6.1,
                'battery': '2775 mAh',
                'high': 14.7,
                'width': 7.1,
                'deep': 0.7,
                'weight': 187,
                'cattegory': 'Phones',
                'main_photo': 'Iphone 12 Pro 256GB Grey_1.jpg',
                'second_photo': 'Iphone 12 Pro 256GB Grey_2.jpg',
                'third_photo': 'Iphone 12 Pro 256GB Grey_3.jpg',
            }

Xiaomi_Redmi_Note_10_Pro_128GB_Onyx_Gray={
                'name': 'Xiaomi Redmi Note 10 128GB Onyx Gray',
                'model': 'Redmi Note 10',
                'price': 339.99,
                'pieces': 15,
                'color': 'Grey',
                'producent': 'Xiaomi',
                'producent_code': 'MZB08KVEU',
                'ean': 6934177730375 ,
                'waterproof': False,
                'system': 'Android 11',
                'processor': 'Qualcomm Snapdragon 732G',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '512 GB',
                'ram': '6 GB',
                'memory': '128 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': "MiniJack 3.5mm",
                'screen': '1080 x 2400 Amoled',
                'screen_diagonal': 6.67,
                'battery': '5020 mAh',
                'high': 16.4,
                'width': 7.6,
                'deep': 0.8,
                'weight': 193,
                'cattegory': 'Phones',
                'main_photo': 'Xiaomi Redmi Note 10 128GB Onyx Gray_1.jpg',
                'second_photo': 'Xiaomi Redmi Note 10 128GB Onyx Gray_2.jpg',
            }

Xiaomi_Redmi_Note_10_Pro_64GB_Onyx_Gray={
                'name': 'Xiaomi Redmi Note 10 64GB Onyx Gray',
                'model': 'Redmi Note 10',
                'price': 309.99,
                'pieces': 15,
                'color': 'Grey',
                'producent': 'Xiaomi',
                'producent_code': '31743',
                'ean': 6934177734465 ,
                'waterproof': False,
                'system': 'Android 11',
                'processor': 'Qualcomm Snapdragon 732G',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '512 GB',
                'ram': '6 GB',
                'memory': '64 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': "MiniJack 3.5mm",
                'screen': '1080 x 2400 Amoled',
                'screen_diagonal': 6.67,
                'battery': '5020 mAh',
                'high': 16.4,
                'width': 7.6,
                'deep': 0.8,
                'weight': 193,
                'cattegory': 'Phones',
                'main_photo': 'Xiaomi Redmi Note 10 64GB Onyx Gray_1.jpg',
                'second_photo': 'Xiaomi Redmi Note 10 64GB Onyx Gray_2.jpg',
            }

Xiaomi_Redmi_Note_10_Pro_64GB_Dual_SIM_Blue={
                'name': 'Xiaomi Redmi Note 10 64GB Blue',
                'model': 'Redmi Note 10',
                'price': 309.99,
                'pieces': 15,
                'color': 'Blue',
                'producent': 'Xiaomi',
                'producent_code': 'xiaomi_20210607155020',
                'ean': 6934177734458 ,
                'waterproof': False,
                'system': 'Android 11',
                'processor': 'Qualcomm Snapdragon 732G',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '512 GB',
                'ram': '6 GB',
                'memory': '64 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': "MiniJack 3.5mm",
                'screen': '1080 x 2400 Amoled',
                'screen_diagonal': 6.67,
                'battery': '5020 mAh',
                'high': 16.4,
                'width': 7.6,
                'deep': 0.8,
                'weight': 193,
                'cattegory': 'Phones',
                'main_photo': 'Xiaomi Redmi Note 10 64GB Blue_1.jpg',
                'second_photo': 'Xiaomi Redmi Note 10 64GB Blue_2.jpg',
            }

Xiaomi_Redmi_Note_10_Pro_64GB_Dual_SIM_Gradient_bronze={
                'name': 'Xiaomi Redmi Note 10 64GB Gradient Bronze',
                'model': 'Redmi Note 10',
                'price': 309.99,
                'pieces': 15,
                'color': 'Gradient Bronze',
                'producent': 'Xiaomi',
                'producent_code': '31751',
                'ean': 7608515832593 ,
                'waterproof': False,
                'system': 'Android 11',
                'processor': 'Qualcomm Snapdragon 732G',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '512 GB',
                'ram': '6 GB',
                'memory': '64 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': "MiniJack 3.5mm",
                'screen': '1080 x 2400 Amoled',
                'screen_diagonal': 6.67,
                'battery': '5020 mAh',
                'high': 16.4,
                'width': 7.6,
                'deep': 0.8,
                'weight': 193,
                'cattegory': 'Phones',
                'main_photo': 'Xiaomi Redmi Note 10 64GB Gradient Bronze_1.jpg',
                'second_photo': 'Xiaomi Redmi Note 10 64GB Gradient Bronze_2.jpg',
            }

Samsung_Galaxy_S20_FE_128GB_Dual_SIM_Blue={
                'name': 'Samsung Galaxy s20 Blue 128GB',
                'model': 'Galaxy s20',
                'price': 609.99,
                'pieces': 15,
                'color': 'Blue',
                'producent': 'Samsung',
                'producent_code': 'SM-G780GZBDEUE',
                'ean': 8806092522770 ,
                'waterproof': True,
                'system': 'Android 10',
                'processor': 'Qualcomm Snapdragon 865',
                'cpu_clock': '2.8 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '1TB',
                'ram': '6 GB',
                'memory': '128 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': "Not Avaiable",
                'screen': '1080 x 2400 Super Amoled',
                'screen_diagonal': 6.5,
                'battery': '4500 mAh',
                'high': 15.9,
                'width': 7.4,
                'deep': 0.8,
                'weight': 193,
                'cattegory': 'Phones',
                'main_photo': 'Samsung Galaxy s20 Blue 128GB_1.jpg',
                'second_photo': 'Samsung Galaxy s20 Blue 128GB_2.jpg',
                'third_photo': 'Samsung Galaxy s20 Blue 128GB_2.jpg',
            }

Samsung_Galaxy_S20_FE_256GB_Dual_SIM_Pink={
                'name': 'Samsung Galaxy s20 Pink 256GB',
                'model': 'Galaxy s20',
                'price': 759.99,
                'pieces': 10,
                'color': 'Pink',
                'producent': 'Samsung',
                'producent_code': 'SM-G780GLVHEUE',
                'ean': 8806092522961,
                'waterproof': True,
                'system': 'Android 10',
                'processor': 'Qualcomm Snapdragon 865',
                'cpu_clock': '2.8 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '1TB',
                'ram': '8 GB',
                'memory': '256 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': "Not Avaiable",
                'screen': '1080 x 2400 Super Amoled',
                'screen_diagonal': 6.5,
                'battery': '4500 mAh',
                'high': 15.9,
                'width': 7.4,
                'deep': 0.8,
                'weight': 193,
                'cattegory': 'Phones',
                'main_photo': 'Samsung Galaxy s20 Pink 256GB_1.jpg',
                'second_photo': 'Samsung Galaxy s20 Pink 256GB_2.jpg',
            }

Samsung_Galaxy_S20_FE_128GB_Dual_SIM_White={
                'name': 'Samsung Galaxy s20 White 128GB',
                'model': 'Galaxy s20',
                'price': 619.99,
                'pieces': 10,
                'color': 'White',
                'producent': 'Samsung',
                'producent_code': 'SM-G780GZWDEUE',
                'ean': 8806090840678,
                'waterproof': True,
                'system': 'Android 10',
                'processor': 'Qualcomm Snapdragon 865',
                'cpu_clock': '2.8 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '1TB',
                'ram': '6 GB',
                'memory': '128 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': "Not Avaiable",
                'screen': '1080 x 2400 Super Amoled',
                'screen_diagonal': 6.5,
                'battery': '4500 mAh',
                'high': 15.9,
                'width': 7.4,
                'deep': 0.8,
                'weight': 193,
                'cattegory': 'Phones',
                'main_photo': 'Samsung Galaxy s20 White 128GB_1.jpg',
                'second_photo': 'Samsung Galaxy s20 White 128GB_2.jpg',
                'third_photo': 'Samsung Galaxy s20 White 128GB_3.jpg',
            }

Sony_Xperia_L4_64GB_Dual_SIM_Black={
                'name': 'Sony Xperia L4 64GB Black',
                'model': 'Xperia L4',
                'price': 179.99,
                'pieces': 20,
                'color': 'Black',
                'producent': 'Sony',
                'producent_code': 'XQAD52M4B.EEAC',
                'ean': 7311271631262,
                'waterproof': False,
                'system': 'Android 9',
                'processor': 'MediaTek Helio P22',
                'cpu_clock': '2.0 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '515GB',
                'ram': '3 GB',
                'memory': '64 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'MiniJack 3.5mm',
                'screen': '720 x 1680 LCD',
                'screen_diagonal': 6.2,
                'battery': '3580 mAh',
                'high': 15.9,
                'width': 7.1,
                'deep': 0.9,
                'weight': 178,
                'cattegory': 'Phones',
                'main_photo': 'Sony Xperia L4 64GB Black_1.jpg',
            }

Samsung_Galaxy_A20e_32GB_Dual_SIM_Black = {
                'name': 'Samsung Galaxy A20e 32GB Black',
                'model': 'Galaxy A20e',
                'price': 229.99,
                'pieces': 18,
                'color': 'Black',
                'producent': 'Samsung',
                'producent_code': 'SM-A202FZKDXEO',
                'ean': 8801643850975,
                'waterproof': False,
                'system': 'Android 9',
                'processor': 'Exynos 7884',
                'cpu_clock': '1.6 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '512GB',
                'ram': '3 GB',
                'memory': '32 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'MiniJack 3.5mm',
                'screen': '720 x 1560 IPS',
                'screen_diagonal': 5.8,
                'battery': '3000 mAh',
                'high': 14.7,
                'width': 6.9,
                'deep': 0.8,
                'weight': 141,
                'cattegory': 'Phones',
                'main_photo': 'Samsung Galaxy A20e 32GB Black_1.jpg',
                'second_photo': 'Samsung Galaxy A20e 32GB Black_2.jpg',
                'third_photo': 'Samsung Galaxy A20e 32GB Black_3.jpg',
            }

Samsung_Galaxy_A20e_32GB_Dual_SIM_Coral = {
                'name': 'Samsung Galaxy A20e 32GB Coral',
                'model': 'Galaxy A20e',
                'price': 229.99,
                'pieces': 18,
                'color': 'Coral',
                'producent': 'Samsung',
                'producent_code': 'SM-A202FZODXEO',
                'ean': 8801643870416,
                'waterproof': False,
                'system': 'Android 9',
                'processor': 'Exynos 7884',
                'cpu_clock': '1.6 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '512GB',
                'ram': '3 GB',
                'memory': '32 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'MiniJack 3.5mm',
                'screen': '720 x 1560 IPS',
                'screen_diagonal': 5.8,
                'battery': '3000 mAh',
                'high': 14.7,
                'width': 6.9,
                'deep': 0.8,
                'weight': 141,
                'cattegory': 'Phones',
                'main_photo': 'Samsung Galaxy A20e 32GB Coral_1.jpg',
                'second_photo': 'Samsung Galaxy A20e 32GB Coral_2.jpg',
                'third_photo': 'Samsung Galaxy A20e 32GB Coral_3.jpg',
            }

Samsung_Galaxy_A20e_32GB_Dual_SIM_Blue = {
                'name': 'Samsung Galaxy A20e 32GB Blue',
                'model': 'Galaxy A20e',
                'price': 229.99,
                'pieces': 18,
                'color': 'Blue',
                'producent': 'Samsung',
                'producent_code': 'SM-A202FZBDXEO',
                'ean': 8801643870553,
                'waterproof': False,
                'system': 'Android 9',
                'processor': 'Exynos 7884',
                'cpu_clock': '1.6 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '512GB',
                'ram': '3 GB',
                'memory': '32 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'MiniJack 3.5mm',
                'screen': '720 x 1560 IPS',
                'screen_diagonal': 5.8,
                'battery': '3000 mAh',
                'high': 14.7,
                'width': 6.9,
                'deep': 0.8,
                'weight': 141,
                'cattegory': 'Phones',
                'main_photo': 'Samsung Galaxy A20e 32GB Blue_1.jpg',
                'second_photo': 'Samsung Galaxy A20e 32GB Blue_2.jpg',
                'third_photo': 'Samsung Galaxy A20e 32GB Blue_3.jpg',
            }

Xiaomi_Mi_11_Lite_128GB_Black = {
                'name': 'Xiaomi Mi 11 Lite 128GB Black',
                'model': 'Mi 11 Lite',
                'price': 329.99,
                'pieces': 12,
                'color': 'Black',
                'producent': 'Xiaomi',
                'producent_code': 'xiaomi_20210421154933',
                'ean': 6934177729638,
                'waterproof': False,
                'system': 'Android 11',
                'processor': 'Qualcomm Snapdragon 732G',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': 'No data',
                'ram': '6 GB',
                'memory': '128 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'Not Avaiable',
                'screen': '1080 x 2400 Amoled',
                'screen_diagonal': 6.55,
                'battery': '4250 mAh',
                'high': 16.05,
                'width': 7.5,
                'deep': 0.7,
                'weight': 157,
                'cattegory': 'Phones',
                'main_photo': 'Xiaomi Mi 11 Lite 128GB Black_1.jpg',
                'second_photo': 'Xiaomi Mi 11 Lite 128GB Black_2.jpg',
                'third_photo': 'Xiaomi Mi 11 Lite 128GB Black_3.jpg',
            }

Xiaomi_Mi_11_Lite_128GB_Blue = {
                'name': 'Xiaomi Mi 11 Lite 128GB Blue',
                'model': 'Mi 11 Lite',
                'price': 329.99,
                'pieces': 12,
                'color': 'Blue',
                'producent': 'Xiaomi',
                'producent_code': 'xiaomi_20210421155922',
                'ean': 6934177732676,
                'waterproof': False,
                'system': 'Android 11',
                'processor': 'Qualcomm Snapdragon 732G',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': 'No data',
                'ram': '6 GB',
                'memory': '128 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'Not Avaiable',
                'screen': '1080 x 2400 Amoled',
                'screen_diagonal': 6.55,
                'battery': '4250 mAh',
                'high': 16.05,
                'width': 7.5,
                'deep': 0.7,
                'weight': 157,
                'cattegory': 'Phones',
                'main_photo': 'Xiaomi Mi 11 Lite 128GB Blue_1.jpg',
                'second_photo': 'Xiaomi Mi 11 Lite 128GB Blue_2.jpg',
            }

Xiaomi_Mi_11_Lite_64GB_Black = {
                'name': 'Xiaomi Mi 11 Lite 64GB Black',
                'model': 'Mi 11 Lite',
                'price': 329.99,
                'pieces': 12,
                'color': 'Black',
                'producent': 'Xiaomi',
                'producent_code': 'xiaomi_20210607143053',
                'ean': 6934177732645,
                'waterproof': False,
                'system': 'Android 11',
                'processor': 'Qualcomm Snapdragon 732G',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': 'No data',
                'ram': '6 GB',
                'memory': '64 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'Not Avaiable',
                'screen': '1080 x 2400 Amoled',
                'screen_diagonal': 6.55,
                'battery': '4250 mAh',
                'high': 16.05,
                'width': 7.5,
                'deep': 0.7,
                'weight': 157,
                'cattegory': 'Phones',
                'main_photo': 'Xiaomi Mi 11 Lite 64GB Black_1.jpg',
                'second_photo': 'Xiaomi Mi 11 Lite 64GB Black_2.jpg',
                'third_photo': 'Xiaomi Mi 11 Lite 64GB Black_3.jpg',
            }

LG_K61_128GB_Dual_SIM_Grey = {
                'name': 'LG K61 128GB Grey',
                'model': 'LG K61',
                'price': 319.99,
                'pieces': 10,
                'color': 'Grey',
                'producent': 'LG',
                'producent_code': '88060870441190',
                'ean': 8806087044614,
                'waterproof': False,
                'system': 'Android 9',
                'processor': 'MediaTek MT6765',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '2TB',
                'ram': '4 GB',
                'memory': '128 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'MiniJack 3.5mm',
                'screen': '1080 x 2340 TN',
                'screen_diagonal': 6.5,
                'battery': '4000 mAh',
                'high': 16.4,
                'width': 7.7,
                'deep': 0.8,
                'weight': 191,
                'cattegory': 'Phones',
                'main_photo': 'LG K61 128GB Grey_1.jpg',
            }

LG_K61_128GB_Dual_SIM_White = {
                'name': 'LG K61 128GB White',
                'model': 'LG K61',
                'price': 319.99,
                'pieces': 10,
                'color': 'White',
                'producent': 'LG',
                'producent_code': '8806087044386',
                'ean': 8806087044386,
                'waterproof': False,
                'system': 'Android 9',
                'processor': 'MediaTek MT6765',
                'cpu_clock': '2.3 GHz Octa Core',
                'memory_card': 'microSD',
                'max_memory_card': '2TB',
                'ram': '4 GB',
                'memory': '128 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'MiniJack 3.5mm',
                'screen': '1080 x 2340 TN',
                'screen_diagonal': 6.5,
                'battery': '4000 mAh',
                'high': 16.4,
                'width': 7.7,
                'deep': 0.8,
                'weight': 191,
                'cattegory': 'Phones',
                'main_photo': 'LG K61 128GB White_1.jpg',
            }

Huawei_P20_Lite_64GB_Dual_SIM_Pink = {
                'name': 'Huawei P20 Lite 64GB Pink',
                'model': 'P20 lite',
                'price': 272.99,
                'pieces': 8,
                'color': 'Pink',
                'producent': 'Huawei',
                'producent_code': 'P20 lite PL',
                'ean': 6901443217427,
                'waterproof': False,
                'system': 'Android 8',
                'processor': 'Huawei Kirin 659',
                'cpu_clock': '2.36 GHz Quad Core',
                'memory_card': 'microSD',
                'max_memory_card': '256GB',
                'ram': '4 GB',
                'memory': '64 GB',
                'modem': '4G LTE',
                'usb': 'Type C',
                'audio_jack': 'MiniJack 3.5mm',
                'screen': '1080 x 2280 TN',
                'screen_diagonal': 5.84,
                'battery': '3000 mAh',
                'high': 14.9,
                'width': 7.1,
                'deep': 0.7,
                'weight': 154,
                'cattegory': 'Phones',
                'main_photo': 'Huawei P20 Lite 64GB Pink_1.jpg',
                'second_photo': 'Huawei P20 Lite 64GB Pink_2.jpg',
            }


phones = [
    iPhone_12_Mini_5G_128GB_Dual_SIM_Blue, 
    iPhone_12_Mini_5G_128GB_Dual_SIM_red, 
    iPhone_12_Pro_512GB_Grey, iPhone_12_Pro_256GB_Grey, 
    Xiaomi_Redmi_Note_10_Pro_128GB_Onyx_Gray, 
    Xiaomi_Redmi_Note_10_Pro_64GB_Onyx_Gray, 
    Xiaomi_Redmi_Note_10_Pro_64GB_Dual_SIM_Blue, 
    Xiaomi_Redmi_Note_10_Pro_64GB_Dual_SIM_Gradient_bronze, 
    Samsung_Galaxy_S20_FE_128GB_Dual_SIM_Blue, 
    Samsung_Galaxy_S20_FE_256GB_Dual_SIM_Pink, 
    Samsung_Galaxy_S20_FE_128GB_Dual_SIM_White, 
    Sony_Xperia_L4_64GB_Dual_SIM_Black,
    Samsung_Galaxy_A20e_32GB_Dual_SIM_Black, 
    Samsung_Galaxy_A20e_32GB_Dual_SIM_Coral, 
    Samsung_Galaxy_A20e_32GB_Dual_SIM_Blue, 
    Xiaomi_Mi_11_Lite_128GB_Black,
    Xiaomi_Mi_11_Lite_64GB_Black,
    Xiaomi_Mi_11_Lite_128GB_Blue,
    LG_K61_128GB_Dual_SIM_Grey,
    LG_K61_128GB_Dual_SIM_White,
    Huawei_P20_Lite_64GB_Dual_SIM_Pink
    ]

"""

from django.core.files import File
from ProductApp.models import *
from ProductApp.products import *
PHONES_PATH = r'electronic_shop/static/images/products/phones/'
for phone in phones:
    phon = Phones.objects.create(**phone)
    phon.main_photo.save(phone['main_photo'], File(open(PHONES_PATH + phone['main_photo'], 'rb')))
    try:
        phon.second_photo.save(phone['second_photo'], File(open(PHONES_PATH + phone['second_photo'], 'rb')))
    except:
        pass
    try:
        phon.third_photo.save(phone['third_photo'], File(open(PHONES_PATH + phone['third_photo'], 'rb')))
    except:
        pass

"""


""" Laptops """
Dell_Vostro_3500_grey_8GB_RAM_I5_Windows10 = {
    'name': 'Dell Vostro 3500 Grey 8GB RAM, I5, Windows10 ',
    'producent': 'Dell',
    'producent_code': 'N3004VN3500EMEA01_2105',
    'ean': 5901165730663,
    'model': 'Vostro 3500',
    'price': 699.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-1135G7',
    'processor_clock' : '2.4 GHz',
    'processor_cores_threads': '4/8',
    'resolution': '1920 x 1080 (Full HD)',
    'energy_time': 2,
    'battery': '42 Wh',
    'screen': 'Mat',
    'screen_diagonal': '15.6"',
    'system': 'Windows 10',
    'graph': 'Intel Iris Xe',
    'disc': 0,
    'ram': 8,
    'ram_model': 'DDR4',
    'max_ram': 32,
    'ram_freq': '3200 MHz',
    'p_c_i_e': '256 GB',
    'wifi': '802.11ac (gen. 5)',
    'bluetooth': True,
    'width': 36.4,
    'deep': 24.9,
    'weight': 1.78,
    'high': 1.8,
    'main_photo': 'Dell Vostro 3500 Grey 8GB RAM, I5, Windows10_1.jpg',
    'second_photo': 'Dell Vostro 3500 Grey 8GB RAM, I5, Windows10_2.jpg',
    'third_photo': 'Dell Vostro 3500 Grey 8GB RAM, I5, Windows10_3.jpg',
 }

Dell_Vostro_3500_black = {
    'name': 'Dell Vostro 3500 black',
    'producent': 'Dell',
    'producent_code': '2_363592',
    'ean': 5901165731608,
    'model': 'Vostro 3500',
    'price': 619.99,
    'pieces': 5,
    'color': 'black',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i3-1115G4',
    'processor_clock' : '3.0 GHz',
    'processor_cores_threads': '2/4',
    'resolution': '1920 x 1080 (Full HD)',
    'energy_time': 2,
    'battery': '42 Wh',
    'screen': 'Mat',
    'screen_diagonal': '15.6"',
    'system': 'Windows 10',
    'graph': 'Intel UHD Graphics Xe G4',
    'disc': 0,
    'ram': 8,
    'ram_model': 'DDR4',
    'max_ram': 16,
    'ram_freq': '2666 MHz',
    'p_c_i_e': '256 GB',
    'wifi': '802.11ac (gen. 5)',
    'bluetooth': True,
    'width': 36.4,
    'deep': 24.9,
    'weight': 1.98,
    'high': 1.99,
    'main_photo': 'Dell_Vostro_3500_black_1.jpg',
    'second_photo': 'Dell_Vostro_3500_black_2.jpg',
    'third_photo': 'Dell_Vostro_3500_black_3.jpg',
 }

Dell_Vostro_3500_16_GB_RAM_256_GB_SSD_Windows_10 = {
    'name': 'Dell Vostro 3500 16 GB RAM 256 GB SSD Windows 10',
    'producent': 'Dell',
    'producent_code': 'N3004VN3500EMEA01_2105',
    'ean': 59011657316081,
    'model': 'Vostro 3500',
    'price': 700.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-1135G7',
    'processor_clock' : '2.4 GHz',
    'processor_cores_threads': '4/8',
    'ram': 16,
    'ram_model': 'DDR4',
    'max_ram': 16,
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '256 GB',
    'graph': 'Intel Iris Xe',
    'screen_diagonal': '15.6"',
    'screen': 'Mat',
    'resolution': '1920 x 1080 (Full HD)',
    'wifi': '802.11ac (gen. 5)',
    'bluetooth': True,
    'energy_time': 2,
    'battery': '42 Wh',
    'system': 'Windows 10',
    'width': 36.4,
    'deep': 24.9,
    'weight': 1.78,
    'high': 1.8,
    'main_photo': 'Dell Vostro 3500 16 GB RAM 256 GB SSD Windows 10_1.jpg',
    'second_photo': 'Dell Vostro 3500 16 GB RAM 256 GB SSD Windows 10_2.jpg',
    'third_photo': 'Dell Vostro 3500 16 GB RAM 256 GB SSD Windows 10_3.jpg',
 }


Laptop_Acer_Nitro_5_AN515_44 = {
    'name': 'Laptop Acer Nitro 5 AN515-44',
    'producent': 'Acer',
    'producent_code': 'NH.Q9GEP.00C',
    'ean': 4710180957747,
    'model': 'Nitro 5',
    'price': 709.99,
    'pieces': 10,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'AMD Ryzen 5 4600H',
    'processor_clock' : '3.0 GHz',
    'processor_cores_threads': '6/12',
    'ram': 8,
    'max_ram': 32,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '512 GB',
    'graph': 'AMD Radeon RX Vega 6',
    'second_graph': 'NVIDIA GeForce GTX 1650',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '55 Wh',
    'energy_time': 10,
    'system': 'Windows 10',
    'width': 36.3,
    'deep': 25.5,
    'weight': 2.2,
    'high': 2.39,
    'main_photo': 'Laptop Acer Nitro 5 AN515-44_1.jpg',
    'second_photo': 'Laptop Acer Nitro 5 AN515-44_2.jpg',
    'third_photo': 'Laptop Acer Nitro 5 AN515-44_3.jpg',
 }


Laptop_Acer_Nitro_5_AN515_44_16_GB_RAM_512_GB_PCIe = {
    'name': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM512 GB M.2 PCIE',
    'producent': 'Acer',
    'producent_code': 'NH.Q9GEP.00C',
    'ean': 4710180957749,
    'model': 'Nitro 5',
    'price': 709.99,
    'pieces': 10,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'AMD Ryzen 5 4600H',
    'processor_clock' : '3.0 GHz',
    'processor_cores_threads': '6/12',
    'ram': 16,
    'max_ram': 32,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '512 GB',
    'graph': 'AMD Radeon RX Vega 6',
    'second_graph': 'NVIDIA GeForce GTX 1650',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '55 Wh',
    'energy_time': 10,
    'system': 'Windows 10',
    'width': 36.3,
    'deep': 25.5,
    'weight': 2.2,
    'high': 2.39,
    'main_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM512 GB M.2 PCIE_1.jpg',
    'second_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM512 GB M.2 PCIE_2.jpg',
    'third_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM512 GB M.2 PCIE_3.jpg',
 }


Laptop_Acer_Nitro_5_AN515_44_16_GB_RAM_1TB_GB_PCIe_Windows_10 = {
    'name': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM 1TB GB M.2 PCIE Windows 10',
    'producent': 'Acer',
    'producent_code': 'NH.Q9GEP.00C',
    'ean': 4710180957748,
    'model': 'Nitro 5',
    'price': 802.99,
    'pieces': 10,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'AMD Ryzen 5 4600H',
    'processor_clock' : '3.0 GHz',
    'processor_cores_threads': '6/12',
    'ram': 16,
    'max_ram': 32,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '1TB',
    'graph': 'AMD Radeon RX Vega 6',
    'second_graph': 'NVIDIA GeForce GTX 1650',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '55 Wh',
    'energy_time': 10,
    'system': 'Windows 10',
    'width': 36.3,
    'deep': 25.5,
    'weight': 2.2,
    'high': 2.39,
    'main_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM 1TB GB M.2 PCIE Windows 10_1.jpg',
    'second_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM 1TB GB M.2 PCIE Windows 10_2.jpg',
    'third_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM 1TB GB M.2 PCIE Windows 10_3.jpg',
 }

Laptop_Acer_Nitro_5_AN515_44_16_GB_RAM_1TB_GB_PCIe = {
    'name': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM 1TB GB M.2 PCIE',
    'producent': 'Acer',
    'producent_code': 'NH.Q9GEP.00C',
    'ean': 471018095774,
    'model': 'Nitro 5',
    'price': 800.99,
    'pieces': 10,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'AMD Ryzen 5 4600H',
    'processor_clock' : '3.0 GHz',
    'processor_cores_threads': '6/12',
    'ram': 16,
    'max_ram': 32,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '1TB',
    'graph': 'AMD Radeon RX Vega 6',
    'second_graph': 'NVIDIA GeForce GTX 1650',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '55 Wh',
    'energy_time': 10,
    'system': 'No system',
    'width': 36.3,
    'deep': 25.5,
    'weight': 2.2,
    'high': 2.39,
    'main_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM 1TB GB M.2 PCIE_1.jpg',
    'second_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM 1TB GB M.2 PCIE_2.jpg',
    'third_photo': 'Laptop Acer Nitro 5 AN515-44 16 GB RAM 1TB GB M.2 PCIE_3.jpg',
 }

Laptop_Gigabyte_G5 = {
    'name': 'Laptop Gigabyte G5',
    'producent': 'Gigabyte',
    'producent_code': 'KC-5EE1130SD',
    'ean': 4719331818555,
    'model': 'G5',
    'price': 1039.99,
    'pieces': 7,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-10500H',
    'processor_clock' : '2.5 GHz',
    'processor_cores_threads': '6/12',
    'ram': 16,
    'max_ram': 64,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '512 GB',
    'graph': 'Intel UHD Graphics 630',
    'second_graph': 'NVIDIA GeForce RTX 3060 Laptop GPU',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '49 Wh',
    'energy_time': 6,
    'system': 'No system',
    'width': 36.1,
    'deep': 25.8,
    'weight': 2.2,
    'high': 2.7,
    'main_photo': 'Laptop Gigabyte G5_1.jpg',
    'second_photo': 'Laptop Gigabyte G5_2.jpg',
    'third_photo': 'Laptop Gigabyte G5_3.jpg',
 }


Laptop_Gigabyte_G5_32_GB_RAM_512_GB_SSD_PCIe = {
    'name': 'Laptop Gigabyte G5 32 GB RAM 512 GB SSD PCIe',
    'producent': 'Gigabyte',
    'producent_code': 'KC-5EE1130SD',
    'ean': 4719331818556,
    'model': 'G5',
    'price': 1299.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-10500H',
    'processor_clock' : '2.5 GHz',
    'processor_cores_threads': '6/12',
    'ram': 32,
    'max_ram': 64,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '512 GB',
    'graph': 'Intel UHD Graphics 630',
    'second_graph': 'NVIDIA GeForce RTX 3060 Laptop GPU',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '49 Wh',
    'energy_time': 6,
    'system': 'No system',
    'width': 36.1,
    'deep': 25.8,
    'weight': 2.2,
    'high': 2.7,
    'main_photo': 'Laptop Gigabyte Laptop G5 32 GB RAM 512 GB SSD PCIe_1.jpg',
    'second_photo': 'Laptop Gigabyte Laptop G5 32 GB RAM 512 GB SSD PCIe_2.jpg',
    'third_photo': 'Laptop Gigabyte Laptop G5 32 GB RAM 512 GB SSD PCIe_3.jpg',
 }

Laptop_Gigabyte_G5_32_GB_RAM_512_GB_SSD_PCIe_Windows_10 = {
    'name': 'Laptop Gigabyte G5 32 GB RAM 512 GB SSD PCIe Windows 10',
    'producent': 'Gigabyte',
    'producent_code': 'KC-5EE1130SD',
    'ean': 4719331818557,
    'model': 'G5',
    'price': 1299.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-10500H',
    'processor_clock' : '2.5 GHz',
    'processor_cores_threads': '6/12',
    'ram': 32,
    'max_ram': 64,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '512 GB',
    'graph': 'Intel UHD Graphics 630',
    'second_graph': 'NVIDIA GeForce RTX 3060 Laptop GPU',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '49 Wh',
    'energy_time': 6,
    'system': 'Windows 10',
    'width': 36.1,
    'deep': 25.8,
    'weight': 2.2,
    'high': 2.7,
    'main_photo': 'Laptop Gigabyte Laptop G5 32 GB RAM 512 GB SSD PCIe Windows 10_1.jpg',
    'second_photo': 'Laptop Gigabyte Laptop G5 32 GB RAM 512 GB SSD PCIe Windows 10_2.jpg',
 }

Laptop_Gigabyte_G5_32_GB_RAM_1_TB_512_GB_SSD_PCIe_Windows_10 = {
    'name': 'Laptop Gigabyte G5 32 GB RAM 1 TB 512 GB SSD PCIe Windows 10 Pro',
    'producent': 'Gigabyte',
    'producent_code': 'KC-5EE1130SD',
    'ean': 4719331818558,
    'model': 'G5',
    'price': 1359.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-10500H',
    'processor_clock' : '2.5 GHz',
    'processor_cores_threads': '6/12',
    'ram': 32,
    'max_ram': 64,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '1 TB + 512 GB',
    'graph': 'Intel UHD Graphics 630',
    'second_graph': 'NVIDIA GeForce RTX 3060 Laptop GPU',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '49 Wh',
    'energy_time': 6,
    'system': 'Windows 10',
    'width': 36.1,
    'deep': 25.8,
    'weight': 2.2,
    'high': 2.7,
    'main_photo': 'Laptop Gigabyte G5 32 GB RAM 1 TB 512 GB SSD PCIe Windows 10 Pro_1.jpg',
    'second_photo': 'Laptop Gigabyte G5 32 GB RAM 1 TB 512 GB SSD PCIe Windows 10 Pro_2.jpg',
    'third_photo': 'Laptop Gigabyte G5 32 GB RAM 1 TB 512 GB SSD PCIe Windows 10 Pro_3.jpg',
 }

Lenovo_IdeaPad_Flex_5_15IIL05_2in1 = {
    'name': 'Lenovo IdeaPad Flex 5 15IIL05',
    'producent': 'IdeaPad',
    'producent_code': '81X30053PB',
    'ean': 195042699999,
    'model': 'IdeaPad Flex 5',
    'price': 582.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-1035G1',
    'processor_clock' : '1 GHz',
    'processor_cores_threads': '4/8',
    'ram': 8,
    'max_ram': 8,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '256 GB',
    'graph': 'Intel UHD Graphics G1',
    'second_graph': 'NVIDIA GeForce RTX 3060 Laptop GPU',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '52 Wh',
    'energy_time': 10.5,
    'system': 'Windows 10 Home',
    'width': 35.8,
    'deep': 23.8,
    'weight': 1.8,
    'high': 1.79,
    'main_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_1.jpg',
    'second_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_2.jpg',
    'third_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_3.jpg',
 }

Lenovo_IdeaPad_Flex_5_15IIL05_8_GB_RAM_512_GB_SSD_PCIe_Windows_10 = {
    'name': 'Lenovo IdeaPad Flex 5 15IIL058 GB RAM 512 GB SSD PCIe Windows 10',
    'producent': 'IdeaPad',
    'producent_code': '81X30053PB',
    'ean': 195042699990,
    'model': 'IdeaPad Flex 5',
    'price': 604.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-1035G1',
    'processor_clock' : '1 GHz',
    'processor_cores_threads': '4/8',
    'ram': 8,
    'max_ram': 8,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '512 GB',
    'graph': 'Intel UHD Graphics G1',
    'second_graph': 'NVIDIA GeForce RTX 3060 Laptop GPU',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '52 Wh',
    'energy_time': 10.5,
    'system': 'Windows 10 Home',
    'width': 35.8,
    'deep': 23.8,
    'weight': 1.8,
    'high': 1.79,
    'main_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_1.jpg',
    'second_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_2.jpg',
    'third_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_3.jpg',
 }

Lenovo_IdeaPad_Flex_5_15IIL05__8_GB_RAM_2_TB_SSD_PCIe_Windows_10_Home = {
    'name': 'Lenovo IdeaPad Flex 5 15IIL05 8 GB RAM 512 GB SSD PCIe Windows 10',
    'producent': 'IdeaPad',
    'producent_code': '81X30053PB',
    'ean': 195042699991,
    'model': 'IdeaPad Flex 5',
    'price': 604.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5-1035G1',
    'processor_clock' : '1 GHz',
    'processor_cores_threads': '4/8',
    'ram': 8,
    'max_ram': 8,
    'ram_model': 'DDR4',
    'ram_freq': '3200 MHz',
    'disc': 0,
    'p_c_i_e': '2 TB',
    'graph': 'Intel UHD Graphics G1',
    'second_graph': 'NVIDIA GeForce RTX 3060 Laptop GPU',
    'screen_diagonal': '15.6"',
    'resolution': '1920 x 1080 (Full HD)',
    'screen': 'Mat',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '52 Wh',
    'energy_time': 10.5,
    'system': 'Windows 10 Home',
    'width': 35.8,
    'deep': 23.8,
    'weight': 1.8,
    'high': 1.79,
    'main_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_1.jpg',
    'second_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_2.jpg',
    'third_photo': 'Lenovo_IdeaPad_Flex_5_15IIL05_2in1_3.jpg',
 }

Apple_MacBook_Air_13_M1_Grey_8GB_RAM_PCIE_256 = {
    'name': 'Apple MacBook Air 13 M1 Grey 8GB RAM PciE 256',
    'producent': 'Apple',
    'producent_code': 'MGN63ZE/A',
    'ean': 194252056370,
    'model': 'MacBook Air 13',
    'price': 1029.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Apple M1',
    'processor_clock' : '3.2 GHz',
    'processor_cores_threads': '8/8',
    'ram': 8,
    'max_ram': 8,
    'ram_model': 'DDR4L',
    'ram_freq': '4266 MHz',
    'disc': 0,
    'p_c_i_e': '256 GB',
    'graph': 'Apple M1',
    'screen_diagonal': '13.3"',
    'resolution': '2560 x 1600 (WQXGA)',
    'screen': 'Shinny',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '50 Wh',
    'energy_time': 18,
    'system': 'macOS',
    'width': 30.4,
    'deep': 21.2,
    'weight': 1.29,
    'high': 1.61,
    'main_photo': 'Apple MacBook Air 13 M1 Grey 8GB RAM PciE 256_1.jpg',
    'second_photo': 'Apple MacBook Air 13 M1 Grey 8GB RAM PciE 256_2.jpg',
    'third_photo': 'Apple MacBook Air 13 M1 Grey 8GB RAM PciE 256_3.jpg',
 }

Apple_MacBook_Air_13_M1_Silver_8GB_RAM_PCIE_256 = {
    'name': 'Apple MacBook Air 13 M1 Silver 8GB RAM PciE 256',
    'producent': 'Apple',
    'producent_code': 'MGN93ZE/A',
    'ean': 194252057605,
    'model': 'MacBook Air 13',
    'price': 1029.99,
    'pieces': 5,
    'color': 'Silver',
    'cattegory': 'Laptops',
    'processor': 'Apple M1',
    'processor_clock' : '3.2 GHz',
    'processor_cores_threads': '8/8',
    'ram': 8,
    'max_ram': 8,
    'ram_model': 'DDR4L',
    'ram_freq': '4266 MHz',
    'disc': 0,
    'p_c_i_e': '256 GB',
    'graph': 'Apple M1',
    'screen_diagonal': '13.3"',
    'resolution': '2560 x 1600 (WQXGA)',
    'screen': 'Shinny',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '50 Wh',
    'energy_time': 18,
    'system': 'macOS',
    'width': 30.4,
    'deep': 21.2,
    'weight': 1.29,
    'high': 1.61,
    'main_photo': 'Apple MacBook Air 13 M1 Silver 8GB RAM PciE 256_1.jpg',
    'second_photo': 'Apple MacBook Air 13 M1 Silver 8GB RAM PciE 256_2.jpg',
    'third_photo': 'Apple MacBook Air 13 M1 Silver 8GB RAM PciE 256_3.jpg',
 }

Apple_MacBook_Air_13_M1_Gold_8GB_RAM_PCIE_256 = {
    'name': 'Apple MacBook Air 13 M1 Gold 8GB RAM PciE 256',
    'producent': 'Apple',
    'producent_code': 'MGND3ZE/A',
    'ean': 194252058831,
    'model': 'MacBook Air 13',
    'price': 1019.99,
    'pieces': 5,
    'color': 'Gold',
    'cattegory': 'Laptops',
    'processor': 'Apple M1',
    'processor_clock' : '3.2 GHz',
    'processor_cores_threads': '8/8',
    'ram': 8,
    'max_ram': 8,
    'ram_model': 'DDR4L',
    'ram_freq': '4266 MHz',
    'disc': 0,
    'p_c_i_e': '256 GB',
    'graph': 'Apple M1',
    'screen_diagonal': '13.3"',
    'resolution': '2560 x 1600 (WQXGA)',
    'screen': 'Shinny',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '50 Wh',
    'energy_time': 18,
    'system': 'macOS',
    'width': 30.4,
    'deep': 21.2,
    'weight': 1.29,
    'high': 1.61,
    'main_photo': 'Apple MacBook Air 13 M1 Gold 8GB RAM PciE 256_1.jpg',
    'second_photo': 'Apple MacBook Air 13 M1 Gold 8GB RAM PciE 256_2.jpg',
    'third_photo': 'Apple MacBook Air 13 M1 Gold 8GB RAM PciE 256_3.jpg',
 }

Apple_MacBook_Air_13_M1_Grey_16GB_RAM_PCIE_512 = {
    'name': 'Apple MacBook Air 13 M1 Grey 16GB RAM PciE 512',
    'producent': 'Apple',
    'producent_code': 'MGN63ZE/A/R1/D1',
    'ean': 5902002140256,
    'model': 'MacBook Air 13',
    'price': 1479.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Apple M1',
    'processor_clock' : '3.2 GHz',
    'processor_cores_threads': '8/8',
    'ram': 16,
    'max_ram': 16,
    'ram_model': 'DDR4L',
    'ram_freq': '4266 MHz',
    'disc': 0,
    'p_c_i_e': '512 GB',
    'graph': 'Apple M1',
    'screen_diagonal': '13.3"',
    'resolution': '2560 x 1600 (WQXGA)',
    'screen': 'Shinny',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '50 Wh',
    'energy_time': 18,
    'system': 'macOS',
    'width': 30.4,
    'deep': 21.2,
    'weight': 1.29,
    'high': 1.61,
    'main_photo': 'Apple MacBook Air 13 M1 Grey 16GB RAM PciE 512_1.jpg',
    'second_photo': 'Apple MacBook Air 13 M1 Grey 16GB RAM PciE 512_2.jpg',
    'third_photo': 'Apple MacBook Air 13 M1 Grey 16GB RAM PciE 512_3.jpg',
 }

Apple_MacBook_Air_13_M1_Grey_16GB_RAM_PCIE_1TB = {
    'name': 'Apple MacBook Air 13 M1 Grey 16GB RAM PciE 1TB',
    'producent': 'Apple',
    'producent_code': 'MGN93ZE/A/R1/D2',
    'ean': 5902002140257,
    'model': 'MacBook Air 13',
    'price': 1479.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Apple M1',
    'processor_clock' : '3.2 GHz',
    'processor_cores_threads': '8/8',
    'ram': 16,
    'max_ram': 16,
    'ram_model': 'DDR4L',
    'ram_freq': '4266 MHz',
    'disc': 0,
    'p_c_i_e': '1TB',
    'graph': 'Apple M1',
    'screen_diagonal': '13.3"',
    'resolution': '2560 x 1600 (WQXGA)',
    'screen': 'Shinny',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '50 Wh',
    'energy_time': 18,
    'system': 'macOS',
    'width': 30.4,
    'deep': 21.2,
    'weight': 1.29,
    'high': 1.61,
    'main_photo': 'Apple MacBook Air 13 M1 Grey 16GB RAM PciE 1TB_1.jpg',
    'second_photo': 'Apple MacBook Air 13 M1 Grey 16GB RAM PciE 1TB_2.jpg',
    'third_photo': 'Apple MacBook Air 13 M1 Grey 16GB RAM PciE 1TB_3.jpg',
 }

Apple_MacBook_Air_13_M1_Gold_16GB_RAM_PCIE_512GB = {
    'name': 'Apple MacBook Air 13 M1 Gold 16GB RAM PciE 512GB',
    'producent': 'Apple',
    'producent_code': 'MGND3ZE/A/R1/D1',
    'ean': 5907595647106,
    'model': 'MacBook Air 13',
    'price': 1499.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Apple M1',
    'processor_clock' : '3.2 GHz',
    'processor_cores_threads': '8/8',
    'ram': 16,
    'max_ram': 16,
    'ram_model': 'DDR4L',
    'ram_freq': '4266 MHz',
    'disc': 0,
    'p_c_i_e': '512 GB',
    'graph': 'Apple M1',
    'screen_diagonal': '13.3"',
    'resolution': '2560 x 1600 (WQXGA)',
    'screen': 'Shinny',
    'wifi': '802.11ax (gen. 6)',
    'bluetooth': True,
    'battery': '50 Wh',
    'energy_time': 18,
    'system': 'macOS',
    'width': 30.4,
    'deep': 21.2,
    'weight': 1.29,
    'high': 1.61,
    'main_photo': 'Apple MacBook Air 13 M1 Gold 16GB RAM PciE 256_1.jpg',
    'second_photo': 'Apple MacBook Air 13 M1 Gold 16GB RAM PciE 256_2.jpg',
    'third_photo': 'Apple MacBook Air 13 M1 Gold 16GB RAM PciE 256_3.jpg',
 }

laptops =[
    # Gigabyte
    Laptop_Gigabyte_G5_32_GB_RAM_1_TB_512_GB_SSD_PCIe_Windows_10,
    Laptop_Gigabyte_G5_32_GB_RAM_512_GB_SSD_PCIe_Windows_10,
    Laptop_Gigabyte_G5_32_GB_RAM_512_GB_SSD_PCIe,
    Laptop_Gigabyte_G5,
    # Acer
    Laptop_Acer_Nitro_5_AN515_44_16_GB_RAM_1TB_GB_PCIe_Windows_10,
    Laptop_Acer_Nitro_5_AN515_44_16_GB_RAM_1TB_GB_PCIe,
    Laptop_Acer_Nitro_5_AN515_44_16_GB_RAM_512_GB_PCIe,
    Laptop_Acer_Nitro_5_AN515_44,
    # Vostro
    Dell_Vostro_3500_16_GB_RAM_256_GB_SSD_Windows_10,
    Dell_Vostro_3500_black,
    Dell_Vostro_3500_grey_8GB_RAM_I5_Windows10,
    # Lenovo
    Lenovo_IdeaPad_Flex_5_15IIL05_2in1,
    Lenovo_IdeaPad_Flex_5_15IIL05_8_GB_RAM_512_GB_SSD_PCIe_Windows_10,
    Lenovo_IdeaPad_Flex_5_15IIL05__8_GB_RAM_2_TB_SSD_PCIe_Windows_10_Home,
    # Apple
    Apple_MacBook_Air_13_M1_Grey_8GB_RAM_PCIE_256,
    Apple_MacBook_Air_13_M1_Silver_8GB_RAM_PCIE_256,
    Apple_MacBook_Air_13_M1_Gold_8GB_RAM_PCIE_256,
    Apple_MacBook_Air_13_M1_Grey_16GB_RAM_PCIE_512,
    Apple_MacBook_Air_13_M1_Grey_16GB_RAM_PCIE_1TB,
    Apple_MacBook_Air_13_M1_Gold_16GB_RAM_PCIE_512GB
]

"""
from django.core.files import File
from ProductApp.models import *
from ProductApp.products import *
LAPTOPS_PATH = r'electronic_shop/static/images/products/laptops/'
for laptop in laptops:
    lap = Laptops.objects.create(**laptop)
    lap.main_photo.save(laptop['main_photo'], File(open(LAPTOPS_PATH + laptop['main_photo'], 'rb')))
    try:
        lap.second_photo.save(laptop['second_photo'], File(open(LAPTOPS_PATH + laptop['second_photo'], 'rb')))
    except:
        pass
    try:
        lap.third_photo.save(laptop['third_photo'], File(open(LAPTOPS_PATH + laptop['third_photo'], 'rb')))
    except:
        pass

"""

""" TV's """

Philips_LED_43_diagonal_4K_Ultra_HD_SAPHI_Ambilight = {
    'name': 'Philips LED 43\' 4K Ultra HD SAPHI Ambilight',
    'producent': 'Philips',
    'producent_code': '43PUS7805/12',
    'ean': 8718863023150,
    'model': '43PUS7805/12',
    'price': 399.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '43\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '60 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'No',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': '92 kWh/Year',
    'high': 58.9,
    'width': 96.7,
    'deep': 18.9,
    'weight': 11.8,
    'main_photo': 'Philips LED 43 diagonal 4K Ultra HD SAPHI Ambilight_1.jpg',
    'second_photo': 'Philips LED 43 diagonal 4K Ultra HD SAPHI Ambilight_2.jpg',
    'third_photo': 'Philips LED 43 diagonal 4K Ultra HD SAPHI Ambilight_3.jpg',
}

Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen = {
    'name': 'Samsung QLED 50\' 4K Ultra HD Tizen',
    'producent': 'Samsung',
    'producent_code': 'QE50Q60TAUXXH',
    'ean': 8806090288173,
    'model': 'QE50Q60TAUXXH',
    'price': 549.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'QLED',
    'diagonal': '50\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': 'No data',
    'high': 72,
    'width': 111.6,
    'deep': 24.3,
    'weight': 13.1,
    'main_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_1.jpg',
    'second_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_2.jpg',
    'third_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_3.jpg',
}

Samsung_QLED_65_diagonal_4K_Ultra_HD_Tizen = {
    'name': 'Samsung QLED 65\' 4K Ultra HD Tizen',
    'producent': 'Samsung',
    'producent_code': 'QE50Q60TAUXXH',
    'ean': 8806090288174,
    'model': 'QE50Q60TAUXXH',
    'price': 769.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'QLED',
    'diagonal': '65\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'high': 90.8,
    'width': 145,
    'deep': 28.9,
    'weight': 22.6,
    'power_consumption': 'No data',
    'main_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_1.jpg',
    'second_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_2.jpg',
    'third_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_3.jpg',
}

Samsung_QLED_75_diagonal_4K_Ultra_HD_Tizen = {
    'name': 'Samsung QLED 75\' 4K Ultra HD Tizen',
    'producent': 'Samsung',
    'producent_code': '75Q60TAUXXH',
    'ean': 8806090300691,
    'model': 'QE50Q60TAUXXH',
    'price': 1439.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'QLED',
    'diagonal': '75\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'high': 104.9,
    'width': 167.5,
    'deep': 35.2,
    'weight': 36.3,
    'power_consumption': '210 kWh/Year',
    'main_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_1.jpg',
    'second_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_2.jpg',
    'third_photo': 'Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen_3.jpg',
}

TCL_QLED_55_diagonal_4K_Ultra_HD_Android = {
    'name': 'TCL QLED 55\' 4K Ultra HD Android',
    'producent': 'TCL',
    'producent_code': '55C715',
    'ean': 5901292514075,
    'model': 'C715',
    'price': 499.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'QLED',
    'diagonal': '55\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'width': 122.9,
    'deep': 7.5,
    'weight': 14.4,
    'high': 76.6,
    'power_consumption': '126 kWh/Year',
    'main_photo': 'TCL QLED 55 4K Ultra HD Android_1.jpg',
    'second_photo': 'TCL QLED 55 4K Ultra HD Android_2.jpg',
    'third_photo': 'TCL QLED 55 4K Ultra HD Android_3.jpg',
}

TCL_QLED_50_diagonal_4K_Ultra_HD_Android = {
    'name': 'TCL QLED 50\' 4K Ultra HD Android',
    'producent': 'TCL',
    'producent_code': '50C715',
    'ean': 5901292514082,
    'model': 'C715',
    'price': 439.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'QLED',
    'diagonal': '50\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'width': 114.4,
    'deep': 7.5,
    'weight': 10.4,
    'high': 69.9,
    'power_consumption': '104 kWh/Year',
    'main_photo': 'TCL QLED 55 4K Ultra HD Android_1.jpg',
    'second_photo': 'TCL QLED 55 4K Ultra HD Android_2.jpg',
    'third_photo': 'TCL QLED 55 4K Ultra HD Android_3.jpg',
}

TCL_QLED_65_diagonal_4K_Ultra_HD_Android = {
    'name': 'TCL QLED 65\' 4K Ultra HD Android',
    'producent': 'TCL',
    'producent_code': '65C715',
    'ean': 5901292514068,
    'model': 'C715',
    'price': 659.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'QLED',
    'diagonal': '55\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': '173 kWh/Year',
    'high': 88.7,
    'width': 144.6,
    'deep': 30,
    'weight': 20.4,
    'main_photo': 'TCL QLED 55 4K Ultra HD Android_1.jpg',
    'second_photo': 'TCL QLED 55 4K Ultra HD Android_2.jpg',
    'third_photo': 'TCL QLED 55 4K Ultra HD Android_3.jpg',
}

Toshiba_LED_58_diagonal_4K_Ultra_HD = {
    'name': 'Toshiba LED 58\' 4K Ultra HD',
    'producent': 'Toshiba',
    'producent_code': '58UA4B63DG',
    'ean': 5055862330524,
    'model': 'UA4B63DG',
    'price': 509.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '58\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 4,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': 'No Data',
    'high': 78.1,
    'width': 129.9,
    'deep': 25,
    'weight': 22,
    'main_photo': 'Toshiba LED 58 4K Ultra HD_1.jpg',
    'second_photo': 'Toshiba LED 58 4K Ultra HD_2.jpg',
}

Toshiba_LED_65_diagonal_4K_Ultra_HD = {
    'name': 'Toshiba LED 65\' 4K Ultra HD',
    'producent': 'Toshiba',
    'producent_code': '65UA4B63DG',
    'ean': 5055862330494,
    'model': 'UA4B63DG',
    'price': 509.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '65\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 4,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': 'No Data',
    'high': 0,
    'width': 0,
    'deep': 0,
    'weight': 0,
    'main_photo': 'Toshiba LED 58 4K Ultra HD_1.jpg',
    'second_photo': 'Toshiba LED 58 4K Ultra HD_2.jpg',
}

Toshiba_LED_43_diagonal_4K_Ultra_HD = {
    'name': 'Toshiba LED 43\' 4K Ultra HD',
    'producent': 'Toshiba',
    'producent_code': '43UA4B63DG',
    'ean': 5055862330432,
    'model': 'UA4B63DG',
    'price': 339.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '43\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 4,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': '78 kWh/year',
    'high': 58.8,
    'width': 96.9,
    'deep': 22,
    'weight': 11,
    'main_photo': 'Toshiba LED 58 4K Ultra HD_1.jpg',
    'second_photo': 'Toshiba LED 58 4K Ultra HD_2.jpg',
}

LG_OLED_48_diagonal_4K_Ultra_HD_WebOS_6 = {
    'name': 'LG OLED 48\' 4K Ultra HD WebOS 6.0',
    'producent': 'LG',
    'producent_code': 'OLED48C11LB',
    'ean': 8806091201911,
    'model': 'OLED48C11LB',
    'price': 1029.99,
    'pieces': 5,
    'color': 'Graphite',
    'cattegory': 'TV',
    'matrix_type': 'OLED',
    'diagonal': '48\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '120 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 4,
    'usb_ports': 3,
    'energy_class': 'G',
    'power_consumption': 'No data',
    'high': 65,
    'width': 107.1,
    'deep': 25.1,
    'weight': 18.9,
    'main_photo': 'LG OLED 48 4K Ultra HD WebOS 6.0_1.jpg',
}

LG_LED_43_diagonal_4K_Ultra_HD_WebOS_6 = {
    'name': 'LG LED 43\' 4K Ultra HD WebOS 6.0',
    'producent': 'LG',
    'producent_code': '43NANO753P',
    'ean': 8806091462237,
    'model': 'NANO753P',
    'price': 479.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '43\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': 'No data',
    'high': 62.2,
    'width': 96.7,
    'deep': 21.6,
    'weight': 9.3,
    'main_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_1.jpg',
    'second_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_2.jpg',
    'third_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_3.jpg',  
}

LG_LED_86_diagonal_4K_Ultra_HD_WebOS_6 = {
    'name': 'LG 86NANO753P LED 86\' 4K Ultra HD WebOS 6.0',
    'producent': 'LG',
    'producent_code': '86NANO753PA',
    'ean': 8806091224576,
    'model': 'NANO753P',
    'price': 2189.99,
    'pieces': 2,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '86\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': 'No data',
    'high': 116.7,
    'width': 192.7,
    'deep': 36.2,
    'weight': 45.9,
    'main_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_1.jpg',
    'second_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_2.jpg',
    'third_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_3.jpg',  
}

LG_LED_75_diagonal_4K_Ultra_HD_WebOS_6 = {
    'name': 'LG 86NANO753P LED 75\' 4K Ultra HD WebOS 6.0',
    'producent': 'LG',
    'producent_code': '75NANO753PA.AEU',
    'ean': 8806091224613,
    'model': 'NANO753P',
    'price': 1819.99,
    'pieces': 3,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '75\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': 'No data',
    'high': 102.7,
    'width': 167.8,
    'deep': 36.2,
    'weight': 32.1,
    'main_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_1.jpg',
    'second_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_2.jpg',
    'third_photo': 'LG LED 43 4K Ultra HD WebOS 6.0_3.jpg',  
}

LG_LED_55_diagonal_8K_Ultra_HD_WebOS_5 = {
    'name': 'LG LED 55\' 8K Ultra HD WebOS 5.0',
    'producent': 'LG',
    'producent_code': 'S0427591',
    'ean': 8806098681525,
    'model': '55NANO956',
    'price': 1429.99,
    'pieces': 3,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '55\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 4,
    'usb_ports': 3,
    'energy_class': 'G',
    'power_consumption': 'No data',
    'high': 77.5,
    'width': 123.5,
    'deep': 28.7,
    'weight': 20.8,
    'main_photo': 'LG LED 55 8K Ultra HD WebOS 5.0_1.jpg',
}

Manta_DLED_24_diagonal_HD_Ready = {
    'name': 'Manta DLED 24\' HD Ready',
    'producent': 'Manta',
    'producent_code': '24LHN79T',
    'ean': 5903089903505,
    'model': '24LHN79T',
    'price': 108.99,
    'pieces': 10,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'DLED',
    'diagonal': '24\'',
    'resolution': '1366 x 768',
    'curved': 'No',
    'hdr': 'No',
    'refresh_rate': '50 Hz',
    'smart_tv': 'No',
    'wifi': 'No',
    'bluetooth': 'No',
    'hdmi_ports': 1,
    'usb_ports': 1,
    'energy_class': 'F',
    'power_consumption': '37 kWh/year',
    'high': 36.8,
    'width': 55.6,
    'deep': 17.6,
    'weight': 3.4,
    'main_photo': 'Manta DLED 24 HD Ready_1.jpg',
    'second_photo': 'Manta DLED 24 HD Ready_2.jpg'
}

Panasonic_LED_58_diagonal_4K_Ultra_HD = {
    'name': 'Panasonic LED 58\' 4K Ultra HD',
    'producent': 'Panasonic',
    'producent_code': 'TX-58HX800E',
    'ean': 5025232912520,
    'model': 'TX-58HX800E',
    'price': 605.99,
    'pieces': 10,
    'color': 'Graphite',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '58\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': '118 kWh/year',
    'high': 82,
    'width': 129.7,
    'deep': 34.5,
    'weight': 21.5,
    'main_photo': 'Panasonic LED 58 4K Ultra HD.jpg',
}

Panasonic_LED_50_diagonal_4K_Ultra_HD = {
    'name': 'Panasonic LED 50\' 4K Ultra HD',
    'producent': 'Panasonic',
    'producent_code': 'TX-58HX800E',
    'ean': 5025232912568,
    'model': 'TX-50GX830E',
    'price': 669.99,
    'pieces': 8,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '50\'',
    'resolution': '3840 x 2160',
    'curved': 'No',
    'hdr': 'Yes',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 3,
    'usb_ports': 2,
    'energy_class': 'G',
    'power_consumption': '85 kWh/year',
    'high': 70.1,
    'width': 112,
    'deep': 39.5,
    'weight': 15,
    'main_photo': 'Panasonic LED 50 4K Ultra HD_1.jpg',
}

Thomson_LED_40_diagonal_Full_HD_Android = {
    'name': 'Thomson LED 40\' Full HD Android',
    'producent': 'Thomson',
    'producent_code': '40FE5606',
    'ean': 5901292512668,
    'model': '40FE5606',
    'price': 291.99,
    'pieces': 8,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '40\'',
    'resolution': '1920 x 1080',
    'curved': 'No',
    'hdr': 'No',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'No',
    'hdmi_ports': 2,
    'usb_ports': 1,
    'energy_class': 'E',
    'power_consumption': '68 kWh/year',
    'high': 57.5,
    'width': 90.5,
    'deep': 19,
    'weight': 6.4,
    'main_photo': 'Thomson LED 40 Full HD Android_1.jpg',
    'second_photo': 'Thomson LED 40 Full HD Android_2.jpg',
}

Thomson_LED_65_diagonal_4K_Ultra_HD_Android = {
    'name': 'Thomson LED 65\' 4K Ultra HD Android',
    'producent': 'Thomson',
    'producent_code': '65UG6400',
    'ean': 5901292514655,
    'model': '65UG6400',
    'price': 291.99,
    'pieces': 5,
    'color': 'Black',
    'cattegory': 'TV',
    'matrix_type': 'LED',
    'diagonal': '40\'',
    'resolution': '1920 x 1080',
    'curved': 'No',
    'hdr': 'No',
    'refresh_rate': '50 Hz',
    'smart_tv': 'Yes',
    'wifi': 'Yes',
    'bluetooth': 'Yes',
    'hdmi_ports': 2,
    'usb_ports': 1,
    'energy_class': 'E',
    'power_consumption': '128 kWh/year',
    'high': 89.9,
    'width': 145.5,
    'deep': 35.2,
    'weight': 18.6,
    'main_photo': 'Thomson LED 65 4K Ultra HD Android_1.jpg',
    'second_photo': 'Thomson LED 65 4K Ultra HD Android_2.jpg',
}




tvs = [
    Philips_LED_43_diagonal_4K_Ultra_HD_SAPHI_Ambilight,
    Samsung_QLED_50_diagonal_4K_Ultra_HD_Tizen,
    Samsung_QLED_65_diagonal_4K_Ultra_HD_Tizen,
    Samsung_QLED_75_diagonal_4K_Ultra_HD_Tizen,
    TCL_QLED_55_diagonal_4K_Ultra_HD_Android,
    TCL_QLED_50_diagonal_4K_Ultra_HD_Android,
    TCL_QLED_65_diagonal_4K_Ultra_HD_Android,
    Toshiba_LED_58_diagonal_4K_Ultra_HD,
    Toshiba_LED_65_diagonal_4K_Ultra_HD,
    Toshiba_LED_43_diagonal_4K_Ultra_HD,
    LG_OLED_48_diagonal_4K_Ultra_HD_WebOS_6,
    LG_LED_43_diagonal_4K_Ultra_HD_WebOS_6,
    LG_LED_86_diagonal_4K_Ultra_HD_WebOS_6,
    LG_LED_75_diagonal_4K_Ultra_HD_WebOS_6,
    # 14
    LG_LED_55_diagonal_8K_Ultra_HD_WebOS_5,
    Manta_DLED_24_diagonal_HD_Ready,
    Panasonic_LED_58_diagonal_4K_Ultra_HD,
    Panasonic_LED_50_diagonal_4K_Ultra_HD,
    Thomson_LED_40_diagonal_Full_HD_Android,
    # 19
    Thomson_LED_65_diagonal_4K_Ultra_HD_Android
    ]

"""
from django.core.files import File
from ProductApp.models import *
from ProductApp.products import *
TV_PATH = r'electronic_shop/static/images/products/tv/'
for tv in tvs:
    tvv = Tv.objects.create(**tv)
    tvv.main_photo.save(tv['main_photo'], File(open(TV_PATH + tv['main_photo'], 'rb')))
    try:
        tvv.second_photo.save(tv['second_photo'], File(open(TV_PATH + tv['second_photo'], 'rb')))
    except:
        pass
    try:
        tvv.third_photo.save(tv['third_photo'], File(open(TV_PATH + tv['third_photo'], 'rb')))
    except:
        pass
"""

""" Pendrives """


SAMSUNG_FIT_PLUS_2020_256GB = {
    'capacity': 256,
    'connector': 'USB 3.1',
    'case': 'Waterproof',
    'name': 'Samsung FIT Plus 2020',
    'price': 40.25,
    'pieces': 10,
    'producent': 'Samsung',
    'producent_code': 'MUF-256AB/APC',
    'ean': 1331141112,
    'color': 'silver',
    'cattegory': 'Pendrives',
    'width': 20,
    'deep': 7.2,
    'weight': 19,
}

#  penek = Pendrives.objects.create(**SAMSUNG_FIT_PLUS_2020_256GB)



""" Pc's"""

Gigabyte_AORUS_Model_X_Core_i9_11900K_16_GB_RTX_3080_2_TB_1_TB_M_2_PCIe = {
    'name': 'Gigabyte AORUS Model X Core i9-11900K, 16 GB, RTX 3080, 2 TB + 1 TB M.2 PCIe',
    'model': 'AORUS Model X',
    'price': 4399,
    'pieces': 5,
    'producent': 'Gigabyte',
    'ean': 4719331819804,
    'processor': 'Core i9-11900K',
    'socket': 'LGA 1200',
    'cooler': 'Water',
    'system': 'No system',
    'graph': 'RTX 3080',
    'chipset': 'Intel Z590',
    'power_suply': 850,
    'mouse': 'No',
    'keyboard': 'No',
    'disc': 0,
    'ram': 16,
    'ram_type': 'DDR4',
    'p_c_i_e': '2 TB + 1 TB',
    'wifi': '802.11 ax', 
    'bluetooth': False,
    'cattegory': 'PC',
    'width': 22.3,
    'deep': 52.1,
    'weight': 17,
    'high': 50,
}

Gigabyte_AORUS_Model_X_Ryzen_9_5900X_32_GB_RTX_3080_2_TB_1_TB_M_2_PCIe = {
    'name': 'Gigabyte AORUS Model X Ryzen 9 5900X, 32 GB, RTX 3080, 2 TB + 1 TB M.2 PCIe',
    'model': 'AORUS Model X',
    'price': 4399,
    'pieces': 5,
    'producent': 'Gigabyte',
    'ean': 4719331819842,
    'processor': 'Ryzen 9 5900X',    
    'socket': 'AM4',
    'cooler': 'Water',
    'system': 'No system',
    'graph': 'RTX 3080',
    'chipset': 'Intel Z590',
    'power_suply': 850,
    'mouse': 'No',
    'keyboard': 'No',
    'disc': 0,
    'ram': 32,
    'ram_type': 'DDR4',
    'p_c_i_e': '2 TB + 1 TB',
    'wifi': '802.11 ax', 
    'bluetooth': False,
    'cattegory': 'PC',
    'width': 280,
    'deep': 170,
    'weight': 1230,
    'high': 39,
}

""" Headphones """

Corsair_HS50_Pro_Stereo_Black = {
    'name': 'Corsair HS50 Pro Stereo',
    'model': 'HS50 Pro',
    'price': 49.34,
    'pieces': 12,
    'producent': 'Corsair',
    'producent_code': 'CA-9011215-EU',
    'ean': 840006610311,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 3.5 mm',
    'cable_lenght': 1.8,
    'microphone': True,
    'color': 'Black',
    'cattegory': 'Headphones',
    'weight': 225,  
}

Corsair_HS50_Pro_Stereo_Blue = {
    'name': 'Corsair HS50 Pro Stereo',
    'model': 'HS50 Pro',
    'price': 49.34,
    'pieces': 12,
    'producent': 'Corsair',
    'producent_code': 'CA-9011217-EU',
    'ean': 840006610359,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 3.5 mm',
    'cable_lenght': 1.8,
    'microphone': True,
    'color': 'Blue',
    'cattegory': 'Headphones',
    'weight': 225,  
}

Corsair_HS50_Pro_Stereo_Green = {
    'name': 'Corsair HS50 Pro Stereo',
    'model': 'HS50 Pro',
    'price': 49.34,
    'pieces': 12,
    'producent': 'Corsair',
    'producent_code': 'CA-9011216-EU',
    'ean': 840006610311,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 3.5 mm',
    'cable_lenght': 1.8,
    'microphone': True,
    'color': 'Green',
    'cattegory': 'Headphones',
    'weight': 225,  
}


Genesis_Neon_360  = {
    'name': 'Genesis Neon 360',
    'model': 'Neon 360',
    'price': 32.99,
    'pieces': 10,
    'producent': 'Genesis',
    'producent_code': 'NSG-1107',
    'ean': 5901969410648,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 2 x 3.5 mm \nUSB',
    'cable_lenght': 2.3,
    'microphone': True,
    'color': 'Red',
    'cattegory': 'Headphones',
    'weight': 390, 
}

Cooler_Master_MH670  = {
    'name': 'HyperX Cloud Orbit S',
    'model': 'Cloud Orbit S',
    'price': 299.99,
    'pieces': 3,
    'producent': 'HyperX',
    'producent_code': 'HX-HSCOS-GM/WW',
    'ean': 740617289664,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 3.5 mm \nUSB \nUSB-C',
    'cable_lenght': 1.5,
    'microphone': True,
    'color': 'Black',
    'cattegory': 'Headphones',
    'weight': 368, 
}

""" Routers """

Cisco_RV260  = {
    'name': 'Cisco RV260',
    'model': 'RV260',
    'price': 172.72,
    'pieces': 2,
    'producent': 'Cisco',
    'producent_code': 'RV260-K9-G5',
    'ean': 882658985928,
    'wifi': False,
    'portable': False,
    'vpn': True,
    'encryption_standard': 'None',
    'wan_ports': '1x RJ45',
    'lan_ports': '8 x 10/100/1000',
    'usb_ports': 0,
    'sim': False,
    'antennas': False,
    'color': 'black',
    'cattegory': 'Routers',
    'width': 280,
    'deep': 170,
    'weight': 1230,
    'high': 39
}

Asus_RT_AX55 = {
    'name': 'Asus RT-AX55',
    'model': 'RT-AX55',
    'price': 76.33,
    'pieces': 10,
    'producent': 'Asus',
    'producent_code': '90IG06C0-BO3100',
    'ean': 4718017728485,
    'wifi': True,
    'wifi_standard': '802.11ax (gen. 6)',
    'wifi_2_4ghz_speed' : '574 Mb/s',
    'wifi_5ghz_speed' : '1200 Mb/s',
    'portable': False,
    'vpn': True,
    'encryption_standard': 'WPA3',
    'wan_ports': '1x RJ45',
    'lan_ports': '4 x 10/100/1000',
    'usb_ports': 0,
    'sim': False,
    'antennas': True,
    'antennas_num' : 4,
    'color': 'black',
    'cattegory': 'Routers',
    'width': 230,
    'deep': 134,
    'weight': 374,
    'high': 56
}

TP_Link_Archer_MR400 = {
    'name': 'TP-Link Archer MR400',
    'model': 'Archer MR400',
    'price': 100.39,
    'pieces': 20,
    'producent': 'TP-Link',
    'producent_code': 'ARCHER MR400',
    'ean': 6935364080679,
    'wifi': True,
    'wifi_standard': '802.11ac (gen. 5)',
    'wifi_2_4ghz_speed' : '300 Mb/s',
    'wifi_5ghz_speed' : '867 Mb/s',
    'portable': False,
    'vpn': True,
    'encryption_standard': 'WPA2',
    'wan_ports': '1x RJ45',
    'lan_ports': '3 x 10/100',
    'usb_ports': 0,
    'sim': True,
    'antennas': True,
    'antennas_num' : 2,
    'color': 'Black',
    'cattegory': 'Routers',
    'width': 202,
    'deep': 141,
    'weight': 260,
    'high': 33.6
}

TP_Link_TL_WR902AC = {
    'name': 'TP_Link_TL_WR902AC ',
    'model': 'TL_WR902AC',
    'price': 28.21,
    'pieces': 3,
    'producent': 'TP-Link',
    'producent_code': 'TL-WR902AC',
    'ean': 6935364095666,
    'wifi': True,
    'wifi_standard': '802.11ac (gen. 5)',
    'wifi_2_4ghz_speed' : '300 Mb/s',
    'wifi_5ghz_speed' : '433 Mb/s',
    'portable': True,
    'vpn': True,
    'encryption_standard': 'WPA2',
    'wan_ports': '1x RJ45',
    'usb_ports': 1,
    'sim': False,
    'antennas': False,
    'color': 'White',
    'cattegory': 'Routers',
    'width': 74,
    'deep': 67,
    'weight': 226,
    'high': 22
}

Tenda_AC23 = {
    'name': 'Tenda AC23',
    'model': 'AC23',
    'price': 47.55,
    'pieces': 13,
    'producent': 'Tenda',
    'producent_code': 'TL-WR902AC',
    'ean': 6932849428438,
    'wifi': True,
    'wifi_standard': '802.11ac (gen. 5)',
    'wifi_2_4ghz_speed' : '300 Mb/s',
    'wifi_5ghz_speed' : '1733 Mb/s',
    'portable': False,
    'vpn': True,
    'encryption_standard': 'WPA2',
    'wan_ports': '3 x 10/100/1000',
    'usb_ports': 0,
    'sim': False,
    'antennas': True,
    'antennas_num' : 7,
    'color': 'Black',
    'cattegory': 'Routers',
    'width': 239,
    'deep': 144,
    'weight': 226,
    'high': 40
}

# from ProductApp.models import *
# router = Routers.objects.create(**Router_Cisco_RV260)