IPHONE_10={
                'name': 'Iphone 10',
                'price': 3000,
                'pieces': 2,
                'ram': 8,
                'memory': 8,
                'modem': 8,
                'color': 'grey',
                'describe': 'The best model',
                'producent': 'Apple',
                'producent_code': 'AABB123',
                'ean': 123456,
                'waterproof': True,
                'distibution': 'EU',
                'system': 'IOS',
                'processor': 'Intel',
                'cpu_clock': '400Mhz',
                'memory_card': '10GB',
                'usb': '3.0',
                'audio_jack': "Yes",
                'screen': '100x200',
                'screen_diagonal': 7.2,
                'battery': 100,
                'high':'10cm',
                'width': '10cm',
                'deep': '10cm',
                'weight': '500g',
                'cattegory': 'Phones'
            }

SAMSUNG_10 = {
                'name': 'Samsung 10',
                'price': 300,
                'pieces': 2,
                'ram': 8,
                'memory': 8,
                'modem': 8,
                'color': 'white',
                'describe': 'The best model',
                'producent': 'Apple',
                'producent_code': 'AABB123',
                'ean': 123455,
                'waterproof': True,
                'system': 'IOS',
                'processor': 'Intel',
                'cpu_clock': '400Mhz',
                'memory_card': '10GB',
                'usb': '3.0',
                'audio_jack': "Yes",
                'screen': '100x200',
                'screen_diagonal': 7.2,
                'battery': 100,
                'high':10,
                'width': 10,
                'deep': 10,
                'weight': 500,
                'cattegory': 'Phones'
            }
# from ProductApp.models import *
# telefon = Phones.objects.create(**SAMSUNG_10)

SAMSUNG_FIT_PLUS_2020_256GB = {
    'capacity': 256,
    'connector': 'USB 3.1',
    'case': 'Waterproof',
    'name': 'Samsung FIT Plus 2020',
    'price': 40.25,
    'pieces': 10,
    'producent': 'Samsung',
    'producent_code': 'MUF-256AB/APC',
    'ean': 1331141112,
    'color': 'silver',
    'cattegory': 'Pendrives',
    'width': 20,
    'deep': 7.2,
    'weight': 19,
}

#  penek = Pendrives.objects.create(**SAMSUNG_FIT_PLUS_2020_256GB)

""" Laptops """

Dell_Vostro_3500_grey = {
    'name': 'Dell Vostro 3500',
    'producent': 'Dell',
    'producent_code': 'N3004VN3500EMEA01_2105',
    'ean': 5901165730663,
    'model': 'Vostro 3500',
    'price': 699.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i5',
    'resolution': '1920 x 1080 (Full HD)',
    'energy_time': 2,
    'battery': 48,
    'screen': 'Mat',
    'screen_diagonal': '15.6"',
    'system': 'No system',
    'graph': 'Intel Iris Xe',
    'disc': 0,
    'ram': 8,
    'ram_model': 'DDR4',
    'p_c_i_e': 256,
    'wifi': '802.11ac (gen. 5)',   
    'width': 36.4,
    'deep': 24.9,
    'weight': 1.78,
    'high': 1.8
 }

Dell_Vostro_3500_black = {
    'name': 'Dell Vostro 3500',
    'producent': 'Dell',
    'producent_code': 'N3001VN3500EMEA01_2201',
    'ean': 5901165731608,
    'model': 'Vostro 3500',
    'price': 700.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i3-1115G4',
    'resolution': '1920 x 1080 (Full HD)',
    'energy_time': 2,
    'battery': 42,
    'screen': 'Mat',
    'screen_diagonal': '15.6"',
    'system': 'Windows 10 Pro',
    'graph': 'Intel UHD Graphics Xe G4',
    'disc': 0,
    'ram': 8,
    'ram_model': 'DDR4',
    'p_c_i_e': 256,
    'wifi': '802.11ac (gen. 5)',   
    'width': 36.4,
    'deep': 24.9,
    'weight': 1.98,
    'high': 1.99
 }

Dell_Vostro_3500_grey_16gb = {
    'name': 'Dell Vostro 3500',
    'producent': 'Dell',
    'producent_code': 'N3001VN3500EMEA01_2201_16',
    'ean': 59011657316081,
    'model': 'Vostro 3500',
    'price': 700.99,
    'pieces': 5,
    'color': 'Grey',
    'cattegory': 'Laptops',
    'processor': 'Intel Core i3-1115G4',
    'resolution': '1920 x 1080 (Full HD)',
    'energy_time': 2,
    'battery': 42,
    'screen': 'Mat',
    'screen_diagonal': '15.6"',
    'system': 'Windows 10 Pro',
    'graph': 'Intel UHD Graphics Xe G4',
    'disc': 0,
    'ram': 16,
    'ram_model': 'DDR4',
    'p_c_i_e': 256,
    'wifi': '802.11ac (gen. 5)',   
    'width': 36.4,
    'deep': 24.9,
    'weight': 1.98,
    'high': 1.99
 }

# from ProductApp.models import *
# lapek = Laptops.objects.create(**Dell_Vostro_3500_grey)

""" Pc's"""

Gigabyte_AORUS_Model_X_Core_i9_11900K_16_GB_RTX_3080_2_TB_1_TB_M_2_PCIe = {
    'name': 'Gigabyte AORUS Model X Core i9-11900K, 16 GB, RTX 3080, 2 TB + 1 TB M.2 PCIe',
    'model': 'AORUS Model X',
    'price': 4399,
    'pieces': 5,
    'producent': 'Gigabyte',
    'ean': 4719331819804,
    'processor': 'Core i9-11900K',
    'socket': 'LGA 1200',
    'cooler': 'Water',
    'system': 'No system',
    'graph': 'RTX 3080',
    'chipset': 'Intel Z590',
    'power_suply': 850,
    'mouse': 'No',
    'keyboard': 'No',
    'disc': 0,
    'ram': 16,
    'ram_type': 'DDR4',
    'p_c_i_e': '2 TB + 1 TB',
    'wifi': '802.11 ax', 
    'bluetooth': False,
    'cattegory': 'PC',
    'width': 22.3,
    'deep': 52.1,
    'weight': 17,
    'high': 50,
}

Gigabyte_AORUS_Model_X_Ryzen_9_5900X_32_GB_RTX_3080_2_TB_1_TB_M_2_PCIe = {
    'name': 'Gigabyte AORUS Model X Ryzen 9 5900X, 32 GB, RTX 3080, 2 TB + 1 TB M.2 PCIe',
    'model': 'AORUS Model X',
    'price': 4399,
    'pieces': 5,
    'producent': 'Gigabyte',
    'ean': 4719331819842,
    'processor': 'Ryzen 9 5900X',    
    'socket': 'AM4',
    'cooler': 'Water',
    'system': 'No system',
    'graph': 'RTX 3080',
    'chipset': 'Intel Z590',
    'power_suply': 850,
    'mouse': 'No',
    'keyboard': 'No',
    'disc': 0,
    'ram': 32,
    'ram_type': 'DDR4',
    'p_c_i_e': '2 TB + 1 TB',
    'wifi': '802.11 ax', 
    'bluetooth': False,
    'cattegory': 'PC',
    'width': 280,
    'deep': 170,
    'weight': 1230,
    'high': 39,
}

""" Headphones """

Corsair_HS50_Pro_Stereo_Black = {
    'name': 'Corsair HS50 Pro Stereo',
    'model': 'HS50 Pro',
    'price': 49.34,
    'pieces': 12,
    'producent': 'Corsair',
    'producent_code': 'CA-9011215-EU',
    'ean': 840006610311,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 3.5 mm',
    'cable_lenght': 1.8,
    'microphone': True,
    'color': 'Black',
    'cattegory': 'Headphones',
    'weight': 225,  
}

Corsair_HS50_Pro_Stereo_Blue = {
    'name': 'Corsair HS50 Pro Stereo',
    'model': 'HS50 Pro',
    'price': 49.34,
    'pieces': 12,
    'producent': 'Corsair',
    'producent_code': 'CA-9011217-EU',
    'ean': 840006610359,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 3.5 mm',
    'cable_lenght': 1.8,
    'microphone': True,
    'color': 'Blue',
    'cattegory': 'Headphones',
    'weight': 225,  
}

Corsair_HS50_Pro_Stereo_Green = {
    'name': 'Corsair HS50 Pro Stereo',
    'model': 'HS50 Pro',
    'price': 49.34,
    'pieces': 12,
    'producent': 'Corsair',
    'producent_code': 'CA-9011216-EU',
    'ean': 840006610311,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 3.5 mm',
    'cable_lenght': 1.8,
    'microphone': True,
    'color': 'Green',
    'cattegory': 'Headphones',
    'weight': 225,  
}


Genesis_Neon_360  = {
    'name': 'Genesis Neon 360',
    'model': 'Neon 360',
    'price': 32.99,
    'pieces': 10,
    'producent': 'Genesis',
    'producent_code': 'NSG-1107',
    'ean': 5901969410648,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 2 x 3.5 mm \nUSB',
    'cable_lenght': 2.3,
    'microphone': True,
    'color': 'Red',
    'cattegory': 'Headphones',
    'weight': 390, 
}

Cooler_Master_MH670  = {
    'name': 'HyperX Cloud Orbit S',
    'model': 'Cloud Orbit S',
    'price': 299.99,
    'pieces': 3,
    'producent': 'HyperX',
    'producent_code': 'HX-HSCOS-GM/WW',
    'ean': 740617289664,
    'bluetooth': False,
    'cable': True,
    'jack': 'Mini Jack 3.5 mm \nUSB \nUSB-C',
    'cable_lenght': 1.5,
    'microphone': True,
    'color': 'Black',
    'cattegory': 'Headphones',
    'weight': 368, 
}

""" Routers """

Cisco_RV260  = {
    'name': 'Cisco RV260',
    'model': 'RV260',
    'price': 172.72,
    'pieces': 2,
    'producent': 'Cisco',
    'producent_code': 'RV260-K9-G5',
    'ean': 882658985928,
    'wifi': False,
    'portable': False,
    'vpn': True,
    'encryption_standard': 'None',
    'wan_ports': '1x RJ45',
    'lan_ports': '8 x 10/100/1000',
    'usb_ports': 0,
    'sim': False,
    'antennas': False,
    'color': 'black',
    'cattegory': 'Routers',
    'width': 280,
    'deep': 170,
    'weight': 1230,
    'high': 39
}

Asus_RT_AX55 = {
    'name': 'Asus RT-AX55',
    'model': 'RT-AX55',
    'price': 76.33,
    'pieces': 10,
    'producent': 'Asus',
    'producent_code': '90IG06C0-BO3100',
    'ean': 4718017728485,
    'wifi': True,
    'wifi_standard': '802.11ax (gen. 6)',
    'wifi_2_4ghz_speed' : '574 Mb/s',
    'wifi_5ghz_speed' : '1200 Mb/s',
    'portable': False,
    'vpn': True,
    'encryption_standard': 'WPA3',
    'wan_ports': '1x RJ45',
    'lan_ports': '4 x 10/100/1000',
    'usb_ports': 0,
    'sim': False,
    'antennas': True,
    'antennas_num' : 4,
    'color': 'black',
    'cattegory': 'Routers',
    'width': 230,
    'deep': 134,
    'weight': 374,
    'high': 56
}

TP_Link_Archer_MR400 = {
    'name': 'TP-Link Archer MR400',
    'model': 'Archer MR400',
    'price': 100.39,
    'pieces': 20,
    'producent': 'TP-Link',
    'producent_code': 'ARCHER MR400',
    'ean': 6935364080679,
    'wifi': True,
    'wifi_standard': '802.11ac (gen. 5)',
    'wifi_2_4ghz_speed' : '300 Mb/s',
    'wifi_5ghz_speed' : '867 Mb/s',
    'portable': False,
    'vpn': True,
    'encryption_standard': 'WPA2',
    'wan_ports': '1x RJ45',
    'lan_ports': '3 x 10/100',
    'usb_ports': 0,
    'sim': True,
    'antennas': True,
    'antennas_num' : 2,
    'color': 'Black',
    'cattegory': 'Routers',
    'width': 202,
    'deep': 141,
    'weight': 260,
    'high': 33.6
}

TP_Link_TL_WR902AC = {
    'name': 'TP_Link_TL_WR902AC ',
    'model': 'TL_WR902AC',
    'price': 28.21,
    'pieces': 3,
    'producent': 'TP-Link',
    'producent_code': 'TL-WR902AC',
    'ean': 6935364095666,
    'wifi': True,
    'wifi_standard': '802.11ac (gen. 5)',
    'wifi_2_4ghz_speed' : '300 Mb/s',
    'wifi_5ghz_speed' : '433 Mb/s',
    'portable': True,
    'vpn': True,
    'encryption_standard': 'WPA2',
    'wan_ports': '1x RJ45',
    'usb_ports': 1,
    'sim': False,
    'antennas': False,
    'color': 'White',
    'cattegory': 'Routers',
    'width': 74,
    'deep': 67,
    'weight': 226,
    'high': 22
}

Tenda_AC23 = {
    'name': 'Tenda AC23',
    'model': 'AC23',
    'price': 47.55,
    'pieces': 13,
    'producent': 'Tenda',
    'producent_code': 'TL-WR902AC',
    'ean': 6932849428438,
    'wifi': True,
    'wifi_standard': '802.11ac (gen. 5)',
    'wifi_2_4ghz_speed' : '300 Mb/s',
    'wifi_5ghz_speed' : '1733 Mb/s',
    'portable': False,
    'vpn': True,
    'encryption_standard': 'WPA2',
    'wan_ports': '3 x 10/100/1000',
    'usb_ports': 0,
    'sim': False,
    'antennas': True,
    'antennas_num' : 7,
    'color': 'Black',
    'cattegory': 'Routers',
    'width': 239,
    'deep': 144,
    'weight': 226,
    'high': 40
}

# from ProductApp.models import *
# router = Routers.objects.create(**Router_Cisco_RV260)