CATTEGORIES = [
    "Laptops",
    "Phones",
    "PC",
    "Monitors",
    "Accesories for laptops",
    "SSD",
    "Graphs",
    "Ram",
    "Pendrives",
    "Routers",
    "Switches",
    "Motherboard",
    "CPU",
    "TV",
    "Headphones",
]

CATTEGORIES_CHOICES = [
    ("Laptops", "Laptops"),
    ("Phones", "Phones"),
    ("PC", "PC"),
    ("Monitors", "Monitors"),
    ("Accesories for laptops", "Accesories for laptops"),
    ("SSD", "SSD"),
    ("Graphs", "Graphs"),
    ("Ram", "Ram"),
    ("Pendrives", "Pendrives"),
    ("Routers", "Routers"),
    ("Switches", "Switches"),
    ("Motherboard", "Motherboard"),
    ("CPU", "CPU"),
    ("TV", "TV"),
    ("Headphones", "Headphones"),
]
