# Generated by Django 3.2 on 2022-01-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0005_alter_mainproductdatabase_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproductdatabase',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
