# Generated by Django 3.2 on 2022-02-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProductApp", "0010_alter_productofthedaydb_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productofthedaydb",
            name="sold_num",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
